storage:
  dbPath: /data/db

net:
  port: 27017
  bindIpAll: true
  tls:
    mode: requireTLS
    certificateKeyFile: /run/mongodb-tls/server.pem
    CAFile: /run/mongodb-tls/ca.crt
    allowConnectionsWithoutCertificates: true

security:
  authorization: enabled
